spring:
    datasource:
        url: 'jdbc:mysql://localhost:3306/gipherdb'
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.MySQL5Dialect
server:
    port: 8095
